### ISSUE TITLE
AttributeError: type object 'Dataset' has no attribute 'load_from_url'

### ISSUE THREAD

**Issue by yasersakkaf** [sergioburdisso/pyss3#25]
Why does it give the following error for the version pyss3-0.6.4 ? Please help

**Comment by sergioburdisso** [comment]
Hi @yasersakkaf! the problem is that the README has been recently updated to include the new function "load_from_url()" but we haven't released the new version of the package that includes it yet. I'll released today and let you know as soon as it is available :blush:.

Thanks for creating this issue Yaser :+1:

**Comment by yasersakkaf** [comment]
Thanks for letting me know

**Comment by Anker-Lee** [comment]
It seems that this error still exist today
